#config/routes.yaml

homepage:
  path: /
  controller: App\Controller\StreambookController::index

profil:
  path: /profil
  controller: App\Controller\ProfilController::index

profil_show:
  path: /profil/show
  controller: App\Controller\ProfilController::show

profil_edit:
  path: /profil/edit
  controller: App\Controller\ProfilController::edit

preference:
  path: /preference
  controller: App\Controller\PreferenceController::index

preference_add:
  path: /preference/add
  controller: App\Controller\PreferenceController::add

preference_show:
  path: /preference/show
  controller: App\Controller\StreambookController::show

preference_remove:
  path: /preference/remove
  controller: App\Controller\PreferenceController::remove

book_add:
  path: /add
  controller: App\Controller\StreambookController::add

book_show:
  path: /show/{url}
  controller: App\Controller\StreambookController::show

book_edit:
  path: /edit/{id}
  controller: App\Controller\StreambookController::edit
  requirements:
    id: '\d+'

book_summarize:
  path: /summarize/{id}
  controller: App\Controller\StreambookController::summarize
  requirements:
    id: '\d+'

book_remove:
  path: /remove/{id}
  controller: App\Controller\StreambookController::remove
  requirements:
    id: '\d+'

book_comment:
  path: /comment/{id}
  controller: App\Controller\StreambookController::comment
  requirements:
    id: '\d+'

page_note:
  path: /note/{id}
  controller: App\Controller\StreambookController::note
  requirements:
    id: '\d+'